# day 1. 파이토치 기본
## 텐서

In [3]:
import torch
import numpy as np

In [4]:
# 5X4의 행렬 생성  => 아무값으로도 초기화되지 않은 기본 메모리 값이 들어감
x = torch.empty(5,4)
print(x)

tensor([[1.4013e-44, 1.5975e-43, 1.3873e-43, 1.4153e-43],
        [4.4842e-44, 1.6255e-43, 1.4153e-43, 1.5274e-43],
        [1.5695e-43, 1.5554e-43, 1.5975e-43, 1.3593e-43],
        [1.5975e-43, 1.4714e-43, 1.5134e-43, 1.6956e-43],
        [4.4842e-44, 1.6395e-43, 1.5414e-43, 1.3593e-43]])


In [5]:
# 모든 값이 1인 3X3의 행렬
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
# 2X1의 값이 0인 행렬
torch.zeros(2)

tensor([0., 0.])

In [7]:
# 5행 6열의 랜덤 텐서
torch.rand(5,6)

tensor([[0.2938, 0.0116, 0.1225, 0.0868, 0.2674, 0.3046],
        [0.8160, 0.6303, 0.8291, 0.9164, 0.5334, 0.2892],
        [0.4509, 0.2959, 0.1792, 0.6688, 0.0321, 0.7997],
        [0.3928, 0.1880, 0.4013, 0.7582, 0.9268, 0.4204],
        [0.4312, 0.0922, 0.4189, 0.3218, 0.7545, 0.4492]])

In [8]:
#리스트
l = [13,4]
#넘파이 어레이
r = np.array([4,56,7])

In [9]:
torch.tensor(l)

tensor([13,  4])

In [10]:
torch.tensor(r)

tensor([ 4, 56,  7])

In [12]:
print(x)
x.size()

tensor([[1.4013e-44, 1.5975e-43, 1.3873e-43, 1.4153e-43],
        [4.4842e-44, 1.6255e-43, 1.4153e-43, 1.5274e-43],
        [1.5695e-43, 1.5554e-43, 1.5975e-43, 1.3593e-43],
        [1.5975e-43, 1.4714e-43, 1.5134e-43, 1.6956e-43],
        [4.4842e-44, 1.6395e-43, 1.5414e-43, 1.3593e-43]])


torch.Size([5, 4])

In [14]:
#사이즈 인덱싱 가능
x.size()[1]

4

In [ ]:
x.size(1)

4

In [15]:
type(x)

torch.Tensor

In [23]:
#같은 모양이면 텐서 더하기 가능
x = torch.rand(2,2) # 2x2 랜덤 행렬
y = torch.rand(2,2) # 2x2 랜덤 행렬
x+y

tensor([[0.8598, 1.2577],
        [0.6849, 1.5143]])

In [24]:
#.add 함수로도 가능
torch.add(x,y)

tensor([[0.8598, 1.2577],
        [0.6849, 1.5143]])

In [25]:
#텐서가 정해진 변수끼리 add로 더하기 가능
#y에 x를 더한다
print(y.add(x))
print(y)

tensor([[0.8598, 1.2577],
        [0.6849, 1.5143]])
tensor([[0.6242, 0.5630],
        [0.2278, 0.6893]])


In [26]:
# add_() => inplace 더한 값으로 y 대체
y.add_(x)

tensor([[0.8598, 1.2577],
        [0.6849, 1.5143]])

### 텐서 크기 변환

In [30]:
# 8*8 행렬 생성
x = torch.rand(8,8)
print(x.size())
print(x)

torch.Size([8, 8])
tensor([[0.3084, 0.0309, 0.1038, 0.2576, 0.3053, 0.3161, 0.4217, 0.4026],
        [0.4166, 0.2132, 0.3144, 0.4019, 0.2279, 0.0575, 0.2057, 0.7623],
        [0.8442, 0.9734, 0.7189, 0.7369, 0.4920, 0.9857, 0.5896, 0.4979],
        [0.4420, 0.0351, 0.1228, 0.5866, 0.3216, 0.5647, 0.2690, 0.2272],
        [0.2728, 0.4696, 0.9992, 0.2875, 0.4293, 0.3431, 0.7191, 0.4664],
        [0.9916, 0.6862, 0.3798, 0.0112, 0.3462, 0.0606, 0.0684, 0.4286],
        [0.5081, 0.9159, 0.3718, 0.6963, 0.5638, 0.0251, 0.0766, 0.1775],
        [0.7521, 0.3088, 0.0569, 0.7469, 0.8699, 0.0278, 0.3952, 0.4326]])


In [34]:
# view() => 크기를 변경 (모양 바꾸기 중요)
a = x.view(16,4)
print(a.size())
print(a)

RuntimeError: shape '[16, 3]' is invalid for input of size 64

In [37]:
# -1은 다른 값에 맞추어 변동 (-1 2개 안됨)
b = x.view(-1,8,4)
print(b.size())

torch.Size([2, 8, 4])


In [38]:
# 넘파이로 바꾸기
y = x.numpy()
type(y)

numpy.ndarray

In [41]:
# item => 숫자가 하나인 텐서를 숫자(float로 변경)
x = torch.ones(1)
print(x)
print(type(x.item()))

tensor([1.])
<class 'float'>
